parameters:
#    mtm_design.example.class: MTM\DesignBundle\Example

services:
#    mtm_design.example:
#        class: %mtm_design.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
