login:
    pattern:   /login
    defaults:  { _controller: "FOSUserBundle:Security:login" }
    
login_check:
    pattern:   /login_check
    
logout:
    path:   /logout
    
registration:
    pattern: /registration
    defaults: { _controller: "FOSUserBundle:Registration:register" }
    
change_password:
    pattern: /change_password
    defaults: { _controller: "FOSUserBundle:ChangePassword:changePassword" }