parameters:
#    mtm_login.example.class: MTM\LoginBundle\Example

services:
#    mtm_login.example:
#        class: %mtm_login.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
