parameters:
#    mtm_profile.example.class: MTM\ProfileBundle\Example

services:
#    mtm_profile.example:
#        class: %mtm_profile.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
