sport:
    pattern: /user/sport
    defaults:  { _controller: "MTMSportBundle:Sport:view" }

add_sport:
    pattern: /user/add_sport
    defaults:  { _controller: "MTMSportBundle:Sport:add" }
    
edit_sport:
    pattern: /user/edit_sport/{idpractice}
    defaults:  { _controller: "MTMSportBundle:Sport:edit" }
    
delete_sport:
    pattern: /user/delete_sport/{idpractice}
    defaults:  { _controller: "MTMSportBundle:Sport:delete" }
    