parameters:
#    mtm_sport.example.class: MTM\SportBundle\Example

services:
#    mtm_sport.example:
#        class: %mtm_sport.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
