_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
   
mtm_registration:
    resource: "@MTMRegistrationBundle/Resources/config/routing.yml"
    prefix:   /

mtm_sport:
    resource: "@MTMSportBundle/Resources/config/routing.yml"
    prefix:   /

mtm_message:
    resource: "@MTMMessageBundle/Resources/config/routing.yml"
    prefix:   /

mtm_comment:
    resource: "@MTMCommentBundle/Resources/config/routing.yml"
    prefix:   /

mtm_profile:
    resource: "@MTMProfileBundle/Resources/config/routing.yml"
    prefix:   /

mtm_login:
    resource: "@MTMLoginBundle/Resources/config/routing.yml"
    prefix:   /
