mtm_design:
    resource: "@MTMDesignBundle/Resources/config/routing.yml"
    prefix:   /

mtm_registration:
    resource: "@MTMRegistrationBundle/Resources/config/routing.yml"
    prefix:   /

mtm_sport:
    resource: "@MTMSportBundle/Resources/config/routing.yml"
    prefix:   /

mtm_message:
    resource: "@MTMMessageBundle/Resources/config/routing.yml"
    prefix:   /

mtm_comment:
    resource: "@MTMCommentBundle/Resources/config/routing.yml"
    prefix:   /

mtm_profile:
    resource: "@MTMProfileBundle/Resources/config/routing.yml"
    prefix:   /

mtm_login:
    resource: "@MTMLoginBundle/Resources/config/routing.yml"
    prefix:   /
    

<<<<<<< HEAD
=======
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
>>>>>>> parent of d7aa5df... Ajout de la gestion des messages et mofification du bundle qui gère


