mtm_registration:
    resource: "@MTMRegistrationBundle/Resources/config/routing.yml"
    prefix:   /

mtm_sport:
    resource: "@MTMSportBundle/Resources/config/routing.yml"
    prefix:   /

mtm_message:
    resource: "@MTMMessageBundle/Resources/config/routing.yml"
    prefix:   /

mtm_comment:
    resource: "@MTMCommentBundle/Resources/config/routing.yml"
    prefix:   /

mtm_profile:
    resource: "@MTMProfileBundle/Resources/config/routing.yml"
    prefix:   /

mtm_login:
    resource: "@MTMLoginBundle/Resources/config/routing.yml"
    prefix:   /
    
profile:
    pattern: /profile/{name}
    defaults: { _controller: MTMProfileBundle:Profile:profile }
 
login:
    pattern:   /login
    defaults:  { _controller: MTMLoginBundle:Login:login }
    
login_check:
    pattern:   /login_check
    
logout:
    path:   /logout



