_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml

mtm_design:
    resource: "@MTMDesignBundle/Resources/config/routing.yml"
    prefix:   /

mtm_sport:
    resource: "@MTMSportBundle/Resources/config/routing.yml"
    prefix:   /

mtm_message:
    resource: "@MTMMessageBundle/Resources/config/routing.yml"
    prefix:   /

mtm_profile:
    resource: "@MTMProfileBundle/Resources/config/routing.yml"
    prefix:   /
    
mtm_comment:
    resource: "@MTMCommentBundle/Resources/config/routing.yml"
    prefix:   /

mtm_core:
    resource: "@MTMCoreBundle/Resources/config/routing.yml"
    prefix:   /
 
mtm_search:
    resource: "@MTMSearchBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /user

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /reset

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /user
    
