jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        MTM\LoginBundle\Entity\TeamMate: 
            algorithm:   sha1
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  login
                check_path:  login_check
                always_use_default_target_path: true
                default_target_path: /user/profile
            logout:
                path:   /logout
                target: /login
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ 


    access_control:
        - { path: ^/user/* , roles: ROLE_USER   }
        - { path: ^/admin/* , roles: ROLE_ADMIN  }

    providers:
        administrators:
            entity: { class: "MTMLoginBundle:TeamMate", property: email }
        in_memory:
            memory:
                users:
                    admin: { password: admin, roles: 'ROLE_ADMIN' }
