parameters:
#    mtm_search.example.class: MTM\SearchBundle\Example

services:
#    mtm_search.example:
#        class: %mtm_search.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
